"""
Write tests for division() function in 2_python_part_2/task_exceptions.py
In case (1,1) it should check if exception were raised
In case (1,0) it should check if return value is None and "Division by 0" printed
If other cases it should check if division is correct

TIP: to test output of print() function use capfd fixture
https://stackoverflow.com/a/20507769
"""


def test_division_ok(capfd):
    ...


def test_division_by_zero(capfd):
    ...


def test_division_by_one(capfd):
    ...
